# Generated by Django 4.1.2 on 2023-05-15 06:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0036_remove_coursestat_avg_rating_course_avg_rating'),
        ('payments', '0003_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Amount of payment.', max_digits=9),
        ),
        migrations.AlterField(
            model_name='payment',
            name='course',
            field=models.ForeignKey(help_text='The course for which the payment was created.', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Payment creation time.'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='id',
            field=models.CharField(help_text='Payment intent ID from StripeAPI.', max_length=27, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='is_success',
            field=models.BooleanField(default=False, help_text='Payment status.'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(help_text='The user for whom the payment was created.', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
    ]
