# Generated by Django 4.1.2 on 2022-11-20 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_teacher_facebook_teacher_google_plus_teacher_twitter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='facebook',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='google_plus',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='twitter',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='vk',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
