# Generated by Django 4.1.2 on 2022-12-14 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_teacher_facebook_alter_teacher_google_plus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='average_rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='facebook',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='google_plus',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='twitter',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='vk',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
