# Generated by Django 4.1.2 on 2022-12-27 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_teacher_average_rating_alter_teacher_facebook_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='photo',
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(default=None, upload_to='teachers/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
