# Generated by Django 4.1.2 on 2023-03-25 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='personal_signature',
            field=models.ImageField(blank=True, default=None, null=True),
        ),
    ]
