# Generated by Django 4.1.2 on 2023-03-27 06:32

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import users.models.ResetPassword


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_teacher_personal_signature'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResetPasswordUrl',
            fields=[
                ('url', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(default=users.models.ResetPassword.add_ten_minutes)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
