# Generated by Django 4.1.2 on 2023-03-27 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_resetpasswordurl'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResetPasswordUrl',
            new_name='ResetPassword',
        ),
    ]
