# Generated by Django 4.1.2 on 2023-03-27 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_rename_resetpasswordurl_resetpassword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resetpassword',
            name='created_at',
        ),
    ]
