# Generated by Django 4.1.2 on 2023-04-03 20:39

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import users.models.ChangeEmail


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_resetpassword_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ChangeEmail',
            fields=[
                ('url', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=128)),
                ('closed_at', models.DateTimeField(default=users.models.ChangeEmail.add_ten_minutes)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
