# Generated by Django 4.1.2 on 2023-04-18 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_user_is_active_changeemail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='personal_signature',
        ),
    ]
