# Generated by Django 4.1.2 on 2023-05-15 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_rename_count_graduates_teacher_count_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='average_rating',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Average rating from all teachers courses.', max_digits=2),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='description',
            field=models.CharField(help_text='Some words about teacher.', max_length=255),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(help_text='User for whom the teacher record is added.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
