# Generated by Django 4.1.2 on 2023-05-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_rename_average_rating_teacher_avg_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeemail',
            name='prev_email',
            field=models.EmailField(default=None, help_text='Current user email.', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='changeemail',
            name='email',
            field=models.EmailField(help_text='New user email.', max_length=128),
        ),
    ]
