# Generated by Django 4.1.2 on 2023-07-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_changeemail_prev_email_alter_changeemail_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeemail',
            name='prev_email',
            field=models.EmailField(blank=True, editable=False, help_text='Current user email.', max_length=128),
        ),
    ]
