# Generated by Django 4.1.2 on 2022-11-29 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='preview',
            field=models.ImageField(default='', upload_to='events/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
