# Generated by Django 4.1.2 on 2022-12-25 09:23

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='created_at',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
