# Generated by Django 4.1.2 on 2023-05-18 17:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0002_feedback_created_at_feedback_is_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='body',
            field=models.TextField(help_text='Message content.'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date of writing the message.'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.EmailField(help_text='Email of the user who wrote.', max_length=128),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='is_closed',
            field=models.BooleanField(default=False, help_text='Has the message been processed.'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(help_text='Full name of the user who wrote.', max_length=255),
        ),
    ]
