# Generated by Django 4.1.2 on 2022-12-25 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_alter_comment_commented_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
    ]
