# Generated by Django 4.1.2 on 2023-03-14 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0007_alter_comment_commented_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commented_type',
            field=models.IntegerField(choices=[(0, 'Курс'), (1, 'Новость'), (2, 'Мероприятие')], max_length=8),
        ),
    ]
