# Generated by Django 4.1.2 on 2023-03-14 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0009_alter_comment_commented_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commented_type',
            field=models.SmallIntegerField(choices=[(0, 'Курс'), (1, 'Новость'), (2, 'Мероприятие')]),
        ),
    ]
