# Generated by Django 4.1.2 on 2023-05-15 13:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0010_alter_comment_commented_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='count_like',
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(help_text='The user who wrote the comment.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(help_text='The text of the comment itself.'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='commented_id',
            field=models.PositiveBigIntegerField(help_text='ID of the object for which the comment is written.'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date the comment was written.'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, default=None, help_text='The rating set by the user along with the comment.', null=True),
        ),
    ]
