# Generated by Django 4.1.2 on 2022-11-19 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=128)),
                ('price', models.FloatField(default=0)),
                ('count_lectures', models.PositiveSmallIntegerField(default=0)),
                ('count_independents', models.PositiveIntegerField(default=0)),
                ('duration', models.PositiveIntegerField(default=1)),
                ('learning_format', models.CharField(choices=[('part', 'Дистанционно'), ('full', 'Очно'), ('both', 'Очно-заочно')], max_length=4)),
                ('preview', models.ImageField(height_field=480, upload_to='courses/%Y/%m/%d/', width_field=854)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
