# Generated by Django 4.1.2 on 2022-11-19 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='learning_format',
        ),
    ]
