# Generated by Django 4.1.2 on 2022-11-19 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_learning_format_alter_course_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='preview',
            field=models.ImageField(upload_to='courses/%Y/%m/%d/'),
        ),
    ]
