# Generated by Django 4.1.2 on 2022-12-07 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_discount_course_shortlesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlesson',
            name='course',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course'),
        ),
        migrations.AlterField(
            model_name='shortlesson',
            name='parent_lesson',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.shortlesson'),
        ),
    ]
