# Generated by Django 4.1.2 on 2022-12-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_alter_shortlesson_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlesson',
            name='custom_id',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
