# Generated by Django 4.1.2 on 2022-12-07 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_shortlesson_custom_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortlesson',
            name='custom_id',
        ),
        migrations.AlterField(
            model_name='shortlesson',
            name='serial_number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
