# Generated by Django 4.1.2 on 2022-12-25 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_alter_course_category_alter_shortlesson_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('count_comments', models.PositiveIntegerField(default=0)),
                ('count_five_rating', models.PositiveIntegerField(default=0)),
                ('count_four_rating', models.PositiveIntegerField(default=0)),
                ('count_three_rating', models.PositiveIntegerField(default=0)),
                ('count_two_rating', models.PositiveIntegerField(default=0)),
                ('count_one_rating', models.PositiveIntegerField(default=0)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
        ),
    ]
