# Generated by Django 4.1.2 on 2022-12-27 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_coursestat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursestat',
            name='avg_rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='coursestat',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='courses.course'),
        ),
    ]
