# Generated by Django 4.1.2 on 2023-01-01 17:36

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_alter_coursestat_avg_rating_alter_coursestat_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
