# Generated by Django 4.1.2 on 2023-01-26 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_rename_course_usercertificate_user_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='learning_format',
            field=models.IntegerField(choices=[(1, 'Дистанционно'), (2, 'Очно'), (3, 'Очно-заочно')]),
        ),
        migrations.AlterField(
            model_name='usercertificate',
            name='certificate',
            field=models.FileField(default=None, null=True, upload_to='certificates/docs/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='usercertificate',
            name='preview',
            field=models.ImageField(default=None, null=True, upload_to='certificates/preview/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='usercertificate',
            name='user_course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='courses.usercourse'),
        ),
    ]
