# Generated by Django 4.1.2 on 2023-01-26 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_alter_course_learning_format_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_body', to='courses.course')),
            ],
        ),
    ]
