# Generated by Django 4.1.2 on 2023-02-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0028_remove_usercourse_is_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourse',
            name='when_completed',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.DeleteModel(
            name='UserCertificate',
        ),
    ]
