# Generated by Django 4.1.2 on 2023-02-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0029_alter_usercourse_when_completed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercourse',
            old_name='lesson_completed',
            new_name='count_independents_completed',
        ),
        migrations.AddField(
            model_name='usercourse',
            name='count_lectures_completed',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
