# Generated by Django 4.1.2 on 2023-04-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0032_rename_when_completed_usercourse_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='count_independents',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usercourse',
            name='completed_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
