# Generated by Django 4.1.2 on 2023-05-14 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0035_alter_discount_end_date_alter_discount_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursestat',
            name='avg_rating',
        ),
        migrations.AddField(
            model_name='course',
            name='avg_rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
