# Generated by Django 4.1.2 on 2023-01-15 18:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lessons', '0006_userlesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='listeners',
            field=models.ManyToManyField(related_name='my_lessons', through='lessons.UserLesson', to=settings.AUTH_USER_MODEL),
        ),
    ]
