# Generated by Django 4.1.2 on 2023-01-18 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0007_lesson_listeners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonbody',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_body', to='lessons.lesson'),
        ),
    ]
