# Generated by Django 4.1.2 on 2023-01-19 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0011_alter_answervalue_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SelectedUserAnswerValue',
        ),
    ]
