# Generated by Django 4.1.2 on 2023-01-21 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0012_delete_selecteduseranswervalue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userattempt',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='userattempt',
            name='user',
        ),
        migrations.AddField(
            model_name='userattempt',
            name='user_lesson',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='lessons.userlesson'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='is_true',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='useranswer',
            unique_together={('user_attempt', 'question')},
        ),
    ]
