# Generated by Django 4.1.2 on 2023-01-21 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0013_remove_userattempt_lesson_remove_userattempt_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userattempt',
            name='user_lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lessons.userlesson'),
        ),
    ]
