# Generated by Django 4.1.2 on 2023-01-26 02:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lessons', '0014_alter_userattempt_user_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answervalue',
            name='is_true',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userattempt',
            name='user_lesson',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='lessons.userlesson'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='userlesson',
            unique_together={('lesson', 'user')},
        ),
    ]
