# Generated by Django 4.1.2 on 2023-02-09 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0018_remove_lesson_is_completed_alter_lesson_lesson_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlesson',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='lessons.lesson'),
        ),
    ]
