# Generated by Django 4.1.2 on 2023-03-31 02:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0021_alter_lesson_course_alter_lesson_lesson_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlesson',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
