# Generated by Django 4.1.2 on 2023-05-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0022_userlesson_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='body',
            field=models.CharField(max_length=512),
        ),
    ]
