# Generated by Django 4.1.2 on 2023-05-08 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0023_alter_question_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlesson',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userlesson',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='userlesson',
            name='completed_at',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='lessons.question'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='user_attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='lessons.userattempt'),
        ),
    ]
