# Generated by Django 4.1.2 on 2023-05-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0024_remove_userlesson_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlesson',
            name='completed_at',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
