# Generated by Django 4.1.2 on 2023-03-14 03:00

from django.db import migrations, models

import resources.models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.ImageField(upload_to=resources.models.Resource.get_file_path),
        ),
        migrations.AlterField(
            model_name='resource',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
