# Generated by Django 4.1.2 on 2023-05-18 17:48

import django.utils.timezone
from django.db import migrations, models

import resources.models.Resource


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_alter_resource_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.ImageField(help_text='The path to the file in the system.', upload_to=resources.models.Resource.get_file_path),
        ),
        migrations.AlterField(
            model_name='resource',
            name='loaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='File upload time.'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='name',
            field=models.CharField(help_text='The file name given by the user.', max_length=255),
        ),
    ]
